name: Title Updater

on:
  repository_dispatch:
    types: [issue-title-update]

jobs:
  update-title:
    runs-on: ubuntu-latest

    steps:
      - name: Update issue title
        uses: actions/github-script@v3
        with:
          script: |
            const issue_number = context.payload.client_payload.issue_number;
            const issue_title = context.payload.client_payload.issue_title;
            github.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              title: `[#${issue_number}] ${issue_title}`
            });
          github-token: ${{ secrets.AUTO_ISSUE_TITLE_NUMBERING }}
